name: Run every day at 08:00
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
        env:
          AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
      - run: go run .
